name: Auto Pull Request, Approve, and Merge
on:
  push:
    branches:
      - actions
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
      
    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.TEST_SECRET }}
        commit-message: 'Automatically created pull request'
        title: 'Auto Pull Request'
        branch: actions
        base: master
        delete-branch: true
    
    - name: create auto approve
      uses: juliangruber/approve-pull-request-action@v1
      with:
        github-token: ${{ secrets.TEST_SECRET }}
        number: ${{ steps.cpr.outputs.pull-request-number }}  
        
    - name: Enable Pull Request Automerge
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.TEST_SECRET }}
        number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: squash
