name: Auto Pull Request, Approve, and Merge
on:
  push:
    branches:
      - actions
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
      
    - name: Create pull request
      id: create_pull_request
      uses: repo-sync/pull-request@v2
      with:
        token: ${{ secrets.TEST_SECRET }}
        commit-message: 'Automatically created pull request'
        title: 'Auto Pull Request'
        head: actions
        base: master
        labels: 'auto-merge'
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v3
      name: create auto approve
      with:
        token: ${{ secrets.TEST_SECRET }}
        pull-request-number: ${{ steps.create_pull_request.outputs.pullRequestNumber }}              
    - name: Merge pull request
      if: steps.create_pull_request.outputs.pull-request-number == 'created'
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.TEST_SECRET }}
        pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
