name: Auto Pull Request, Approve, and Merge
on:
  push:
    branches:
      - actions
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
      
    - name: Create pull request
      id: create_pull_request
      uses: repo-sync/pull-request@v2
      with:
        token: ${{ secrets.TEST_SECRET }}
        commit-message: 'Automatically created pull request'
        title: 'Auto Pull Request'
        head: actions
        base: master
        labels: 'auto-merge'
    - uses: juliangruber/merge-pull-request-action@v1
      name: create auto approve
      with:
        github-token: ${{ secrets.TEST_SECRET }}
        number: ${{ steps.create_pull_request.outputs.pull-request-number }}              
    - name: Merge pull request
      if: steps.create_pull_request.outputs.pull-request-number == 'created'
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.TEST_SECRET }}
        pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
