name: Auto Pull Request, Approve, and Merge
on:
  push:
    branches:
      - actions
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
    
    - name: Bump release version
      run: |
          echo "NEW_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
          
    # Update changelog unreleased section with new version
    - name: Update changelog
      uses: superfaceai/release-changelog-action@v1
      with:
          path-to-changelog: CHANGELOG.md
          version: ${{ env.NEW_VERSION }}
          operation: release
          
   # Commit changes
    - name: Commit CHANGELOG.md and package.json changes and create tag
      run: |
          git add "CHANGELOG.md"
          git commit -m "${{ env.NEW_VERSION }}"
    
   # Push repository changes
    - name: Push changes to repository
      env:
          GITHUB_TOKEN: ${{ secrets.TEST_SECRET }}
      run: |
         git push origin master:actions && git push origin master:actions 
          
    - name: Create pull request
      id: cpr
      uses: repo-sync/pull-request@v2
      with:
        token: ${{ secrets.TEST_SECRET }}
        commit-message: 'Automatically created pull request'
        title: 'Auto Pull Request'
        branch: actions
        base: master
        delete-branch: true
        
    - uses: juliangruber/merge-pull-request-action@v1
      name: create auto approve
      with:
        github-token: ${{ secrets.TEST_SECRET }}
        number: ${{ steps.cpr.outputs.pr_number }}              
    - name: Merge pull request
      if: steps.cpr.outputs.pr_number == 'created'
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.TEST_SECRET }}
        pull-request-number: ${{ steps.cpr.outputs.pr_number }}
        method: squash
        
   
   
    
    
